app: ${env:PROJECT_NAME}

service: ${env:PROJECT_NAME}

plugins:
  - serverless-domain-manager
  - serverless-hosted-zone
  - serverless-certificate-creator
  - fullstack-serverless

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: get /
custom:
  hostedZone:
    name: ${env:CLIENT_URL}.
  customCertificate:
    hostedZoneNames: '${env:CLIENT_URL}.'
    certificateName: '${env:CLIENT_URL}'
    subjectAlternativeNames : 
      - 'www.${env:CLIENT_URL}'
      - 'api.${env:CLIENT_URL}'
    region: us-east-1
  customDomain:
    domainName: api.${env:CLIENT_URL}
    certificateName: ${env:CLIENT_URL}
    createRoute53Record: true
    autoDomain: true
  fullstack:
    domain: ${env:CLIENT_URL}
    certificate: ${certificate(${self:custom.customCertificate.certificateName}):CertificateArn}
    bucketName: ${env:PROJECT_NAME}-bucket
    distributionFolder: ../frontend/build 
    indexDocument: index.html
    errorDocument: error.html
    singlePageApp: true
    compressWebContent: true
